### PR TITLE
Fixed Backwards compatibility

### PR DESCRIPTION
**Pull request by burdoto**
https://github.com/xdrop/fuzzywuzzy/pull/47#issuecomment-434409264

### CODE REVIEW

**Comment by burdoto** [comment]
and before you ask:
NO, i have NOTHING better to do with my time than sit in  front on my pc and wait for people on github to respond to my stuff xD im refactoring my project which is quite exhausting

**Comment by xdrop** [comment]
Haha, no worries - appreciate the help!

Is this different to c63c904bd29abc1ad50bde4aacf08a0dc4af499a?

**Comment by burdoto** [comment]
This is different, this PR reverts some of the changes made.
This PR adds the second `BoundExtractedResult` object and reverts the changes on the old one

**Comment by xdrop** [comment]
Is this ready for merge?

**Comment by burdoto** [comment]
yes

**Comment by burdoto** [comment]
well the check succeeded, so i guess its ready :p i usually dont open half done PRs without a [WIP]

**Comment by burdoto** [comment]
Basically what is the case that the `develop` branch now has the "newer" version already, so i suggest building from there instead of rebasing as this commit here would revert all progress.

other way you could rebase and then add a revertcommit that reverts THIS [6017838]

**Pull request merged**
