### PR TITLE
Updated version attribute to 2.0.0; also deleted deprecated classes

### PR DESCRIPTION
**Pull request by burdoto**
I have a question:
Should this new major version be on Java 8 instead, then it would be possible to:
- Annotate the `ToStringFunction`-interface as a `@FunctionalInterface`
- Completely change the custom interface to `java.util.Function<String, T>`

I mean, Java 11 has been released, so maybe it would be time to leave old versions behind. Your decision

### CODE REVIEW

**Comment by xdrop** [comment]
My main concern was Android since a lot of projects using this are Android based. There is varying degrees of [Java 8 support](https://developer.android.com/studio/write/java8-support) depending on what Android version we want to target. For example `java.util.Function` needs minimum Android 7.0 which might be a bit too restrictive. I've also considered moving to Kotlin since by default it targets Java 1.6, but would have to ensure there is no performance loss from doing so (worst case I leave diffutils in Java).

We can move to Java 1.8 for now, and I'll try and do some more research to decide.

**Comment by xdrop** [comment]
Do you still need me to apply the revert of 6017838 to `develop`?

**Comment by burdoto** [comment]
Android 7 is about 20 % of all android devices, as i would estimate

**Comment by burdoto** [comment]
i could open a rebasing/reverting pr myself later, but that is not required at this point in time.

i was starting to think about the long open issue with PartialRatio but i cant get intellij to properly dependent the diffutils package, so im taking a short break

**Comment by xdrop** [comment]
Sure, no worries I've shared some screens in [gitter](https://gitter.im/fuzzywuzzy_java) for how the dependecy is set up. You can message me there so we avoid spamming the issues if you want.

**Comment by burdoto** [comment]
This can be merged

**Comment by burdoto** [comment]
Will add those changes to #50

**Pull request closed without merging**
